### ISSUE TITLE
Knoppen in de linker kolom zijn niet goed uitgelijnd wanneer '3 kolommen' is aangevinkt

### ISSUE THREAD

**Issue by dpvanbalen** [Koenvh1/WIDM-Exam#1]
De code voor die knoppen is ook verrassend anders dan de omliggende code, dit lijkt de logische oplossing in /WIDM Exam/FrmTest.vb:

```
git diff
@@ -301,7 +301,8 @@ Public Class FrmTest
                                        192)
             Else
                 _b.Location = New Point(96,
-                                       Spacebetweenanswers * (_locationValue - 1) + 190 + FrmOpenTest.DpiPercent.Text - 96)
+                                       Spacebetweenanswers * (_locationValue - 1) + 190 + (FrmOpenTest.DpiPercent.Text * 2) -
+                                       192)
             End If
```

Ik heb alleen momenteel geen manier om WIDM-Exam zelf te compilen om dit te testen.

**Comment by Koenvh1** [comment]
Wat klopt er niet aan de uitlijning? 
![image](https://user-images.githubusercontent.com/5168825/76688770-39a80f00-6630-11ea-8939-fc026d337b60.png)

**Comment by dpvanbalen** [comment]
Ik weet niet waar het precies aan ligt, misschien is het dat 'DpiPercent' bij mij een andere waarde heeft, maar bij mij ziet het er zo uit:
![Untitled](https://user-images.githubusercontent.com/14198026/76688793-8ee42080-6630-11ea-9e82-858010b72cd6.png)

Met de bovenstaande wijziging heeft elke kolom dezelfde formule, dus het klinkt alsof dat op elk scherm/elke computer zou werken.

**Comment by Koenvh1** [comment]
Klopt, ik zie het nu ook (op 125%). Zou nu opgelost moeten zijn:
[WIDM Exam.zip](https://github.com/Koenvh1/WIDM-Exam/files/4333253/WIDM.Exam.3.zip)

**Comment by Koenvh1** [comment]
De nieuwe versie staat nu ook online
